apiVersion: apps/v1
kind: Deployment
metadata:
  name: lataupe-bunker-tech
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lataupe-bunker-tech
  template:
    metadata:
      labels:
        app: lataupe-bunker-tech
    spec:
      containers:
      - name: lataupe-bunker-tech
        image: lataupe-bunker-tech:latest
        ports:
        - containerPort: 5001
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: lataupe-bunker-secrets
              key: secret-key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: lataupe-bunker-secrets
              key: database-url
        - name: PORT
          value: "5001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: lataupe-bunker-tech-service
  namespace: default
spec:
  selector:
    app: lataupe-bunker-tech
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: lataupe-bunker-secrets
  namespace: default
type: Opaque
data:
  secret-key: YnVua2VyLXRlY2gtc3VwZXItc2VjcmV0LWtleS0yMDI1  # base64 encoded
  database-url: c3FsaXRlOi8vL2J1bmtlci5kYg==  # base64 encoded sqlite:///bunker.db
